experiencein/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('perfis.urls')),
    path('', include('usuarios.urls'))
]

perfis/urls.py
from django.urls import path, re_path
from perfis import views

urlpatterns = [
	path('', views.index, name='index'),
	path('perfis/<int:perfil_id>', views.exibir, name='exibir'),
	# re_path(r'^perfis/\d+$', views.exibir, name='perfis')
	path('perfis/<int:perfil_id>/convidar', views.convidar, name='convidar'),
	path('convite/<int:convite_id>/aceitar', views.aceitar, name='aceitar')
]

usuarios/urls.py
# experiencein/usuarios/urls.py 

from django.urls import path
from usuarios.views import RegistrarUsuarioView
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
    path('registrar/', RegistrarUsuarioView.as_view(), name='registrar'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
	path('logout/', LogoutView.as_view(), name='logout')
]

perfis/models.py
from django.db import models
from django.contrib.auth.models import User

class Perfil(models.Model):

	nome = models.CharField(max_length=255, null=False)
	#email = models.CharField(max_length=255, null=False)
	telefone = models.CharField(max_length=15, null=False)
	nome_empresa = models.CharField(max_length=255, null=False)
	contatos = models.ManyToManyField('self')

	usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name="perfil")

	@property
	def email(self):
		return self.usuario.email

	def convidar(self, perfil_convidado):
		Convite(solicitante=self, convidado=perfil_convidado).save()

class Convite(models.Model):
	solicitante = models.ForeignKey(Perfil, on_delete=models.CASCADE, related_name='convites_feitos')
	convidado = models.ForeignKey(Perfil, on_delete=models.CASCADE, related_name='convites_recebidos')

	def aceitar(self):
		self.convidado.contatos.add(self.solicitante)
		self.solicitante.contatos.add(self.convidado)
		self.delete()

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):

    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False

        user_exists = User.objects.filter(username=self.data['nome']).exists()

        if user_exists:
            self.adiciona_erro('Usuario ja existente')
            valid = False

        return valid
        
    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

perfis/views.py
from django.shortcuts import render, redirect
from perfis.models import Perfil, Convite

from django.contrib.auth.decorators import login_required

from django.contrib.auth.decorators import permission_required

@login_required
def index(request):
	
	return render(request, 'index.html', {'perfis': Perfil.objects.all(), 'perfil_logado': get_perfil_logado(request)})

@login_required
def exibir(request, perfil_id):	
	perfil = Perfil.objects.get(id=perfil_id)

	perfil_logado = get_perfil_logado(request)
	ja_e_contato = perfil in perfil_logado.contatos.all()
	
	return render(request, 'perfil.html', {'perfil' : perfil, 'perfil_logado' : get_perfil_logado(request), 'ja_e_contato' : ja_e_contato})


@login_required
def convidar(request, perfil_id):
	perfil_a_convidar = Perfil.objects.get(id=perfil_id)
	perfil_logado = get_perfil_logado(request)
	perfil_logado.convidar(perfil_a_convidar)
	return redirect('index')

@login_required
def aceitar(request, convite_id):
	convite = Convite.objects.get(id=convite_id)
	convite.aceitar()
	return redirect('index')

@login_required
def get_perfil_logado(request):
	return request.user.perfil

usuarios/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic.base import View
from perfis.models import Perfil
from usuarios.forms import RegistrarUsuarioForm

class RegistrarUsuarioView(View):
    template_name = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):

        #preenche o from
        form = RegistrarUsuarioForm(request.POST)

        #verifica se eh valido
        if form.is_valid():

            dados_form = form.data

            #cria o usuario
            usuario = User.objects.create_user(dados_form['nome'], dados_form['email'], dados_form['senha'])            

            #cria o perfil
            perfil = Perfil(nome=dados_form['nome'],
                            telefone=dados_form['telefone'],
                            nome_empresa=dados_form['nome_empresa'],
                            usuario=usuario)

            #grava no banco
            perfil.save()

            #redireciona para index
            return redirect('index')

        #so chega aqui se nao for valido
        #vamos devolver o form para mostrar o formulario preenchido 
        return render(request, self.template_name, {'form' : form})

perfis/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">	
	<link rel="stylesheet" href="{% static "styles/bootstrap.css" %}">
	<link rel="stylesheet" href="{% static "styles/main.css" %}">
	<title>ExperienceIn</title>
</head>
<body>
	<div class="container">
		<div class="header">
			<ul class="nav nav-pills pull-right">
				<li><a href="{% url 'index' %}">{{ perfil_logado.nome }}</a></li>
				<li><a href="/logout/">Logout</a></li>
			</ul>
			<h3 class="text-muted">ExperienceIn</h3>
		</div>
		<div class="row content">
			{% block body %}	
			{% endblock %}
		</div>
	</div>

</body>
</html>

perfis/templates/index.html
{% extends "base.html" %}
{% block body %}
<div class="col-lg-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			<strong>Todos os Perfis</strong>
		</div>
		{% if perfis %}
		<ul>
			{% for perfil in perfis %}
			<li>
				<a href="{% url 'exibir' perfil.id %}">{{perfil.nome}}</a> / {{perfil.email}}
			</li>
			{% endfor %}
		</ul>
		{% else %}
		<p>Nenhum perfil encontrado</p>
		{% endif %}
	</div>
	<div class="panel panel-default">
		{% with total_de_convites=perfil_logado.convites_recebidos.count %}
			{% if total_de_convites %}
				<div class="panel-heading">
					<strong>Você tem {{ total_de_convites }} convite{{ total_de_convites|pluralize}} aguardando aprovação</strong>
				</div>
				<ul class="list-group">
					{% for convite in perfil_logado.convites_recebidos.all %}
						<li class="list-group-item">
							{{ convite.solicitante.nome }}
							<a href="{% url 'aceitar' convite.id %}" class="pull-right">aceitar</a>
						</li>
					{% endfor %}
				</ul>
			{% else %}
				<div class="panel-body">
					<p>Nenhum convite recebido :(</p>
				</div>
			{% endif %}
		{% endwith %}
	</div>

	<div class="panel panel-default">
		{% with total_de_contatos=perfil_logado.contatos.count %}
			{% if total_de_contatos %}
				<div class="panel-heading">
					<strong>Você tem {{ total_de_contatos }} contato{{ total_de_contatos|pluralize}}</strong>
				</div>
				<ul class="list-group">
					{% for contato in perfil_logado.contatos.all %}
						<li class="list-group-item">
							<a href="{% url 'exibir' contato.id %}">{{contato.nome}}</a>
						</li>
					{% endfor %}
				</ul>
			{% else %}
				<div class="panel-body">
					<p>Você não possui contatos no momento :(</p>
				</div>
			{% endif %}
		{% endwith %}
	</div>

</div>
{% endblock %}

perfis/templates/perfil.html
{% extends "base.html" %}
{% block body %}
<div class="row">
	<div class="col-lg-12">
		<h2 style="margin-top: 0">{{ perfil.nome }}</h2>
		<address>
			<strong>{{ perfil.nome_empresa }}</strong><br>
			<abbr title="Telefone">Tel:</abbr> {{ perfil.telefone }}<br>
			<a href="mailto:{{ perfil.email }}">{{ perfil.email }}</a>
		</address>

		{% if ja_e_contato %}
			<div class="well well-sm">Vocês estão conectados!</div>
		{% else %}
			<a href="{% url 'convidar' perfil.id %}" class="btn btn-success" role="button">convidar</a>
		{% endif %}
	</div>
</div>
{% endblock %}

usuarios/templates/base_usuario.html
<!-- experiencein/usuarios/templates/base_usuario.html -->

{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">

        <title>ExperienceIn</title>

        <link href="{% static 'styles/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'styles/signin.css' %}" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            {% block body %}

            {% endblock %} 
        </div>
    </body>
</html>

usuarios/templates/login.html
<!-- experiencein/usuarios/templates/login.html -->

{% extends "base_usuario.html" %}

{% block body %}

    <form class="form-signin" role="form" action="{% url 'login' %}" method="post">
        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome de usuário" required autofocus>

        <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

        <input type="hidden" name="next" value="{{ next }}" />

        {% if form.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Por favor, verifique o Email e/ou Senha informados
          </div>
        {% endif %}

        <a href="{% url 'registrar' %}">registre-se</a>
    </form>

{% endblock %}

usuarios/templates/registrar.html
<!-- experiencein/usuarios/templates/registrar.html -->

{% extends "base_usuario.html" %}

{% block body %}

  <form class="form-signin" action="{% url 'registrar' %}" method="post">

    {% csrf_token %}

    <h2 class="form-signin-heading">Crie seu usuário</h2>

    <input type="text" id="id_email" name="email" class="form-control" placeholder="Email *" required autofocus>

    <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Nome de usuário*" required >

    <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha *" required>

    <hr />

    <input type="text" id="id_telefone" name="telefone" class="form-control" placeholder="Telefone">

    <input type="text" id="id_nome_empresa" name="nome_empresa" class="form-control" placeholder="Empresa">

    <hr />

    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>

    <hr/>

     {% if form.errors %}
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{form.non_field_errors}}
      </div>
    {% endif %}
  </form>

{% endblock %}